### PR TITLE
Fixes #12 by removing specific constraint code

### LINKED ISSUE #12: crash on rotation
I'm getting a crash on rotation at line 49 in ActionCell.swift.
      actionTitleLabelConstraintToImageView?.priority = UILayoutPriorityDefaultHigh

the error I'm getting is:

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Mutating a priority from required to not on an installed constraint (or vice-versa) is not supported.  You passed priority 1000 and the existing priority was 1000.'
*** First throw call stack:

### PR DESCRIPTION
**Pull request by m-revetria**
Fixes issue #12.

The crash is caused because `ActionCell` is changing the priority from some constraints from Required to Optional and viceversa when they are already installed. This can happen when the `setup` method is called twice, and the second time passing a null image. These constraints control how the cell's title label is positioned taking into account if the cell has or not an image.

I just removed these constraint from the base class `ActionCell` instead of trying to change the constraints properties in some way. I opted for removing them because they add specific dependent  code on how the cell's UI is designed and should be out of the scope of this class. This way we are avoiding coupling XLActionController base code with specific actions' UI code.

>To see how this can be implemented, developers can take a look to TwitterCell

Note: this is a breaking change. If this PR is merged then, **apps that are using these constraint it will crash with the exception** "this class is not key value coding-compliant for the key..."

```
2016-09-05 14:44:22.837 Example[6518:267146] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<Example.YoutubeCell 0x7fc469e62320> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key actionTitleLabelConstraintToContainer.'
```

### CODE REVIEW

File: Example/CustomActionControllers/Twitter.swift [hunk 1]
```diff
@@ -42,7 +44,19 @@ public class TwitterCell: ActionCell {
         super.awakeFromNib()
         initialize()
     }
-    
+
+    public override func setup(title: String?, detail: String?, image: UIImage?) {
+        super.setup(title, detail: detail, image: image)
+
+        if let _ = image {
+            imageViewWidthConstraint.constant = 36
```
Comment (mtnbarreto) [inline Example/CustomActionControllers/Twitter.swift]:
```
imageViewWidthConstraint.constant = image != nil ? 36 : 0
```
